--Find total customers by countries
SELECT
     country,
     COUNT(customer_key)
FROM gold.dim_customers
GROUP BY country

--Find total customers by gender
SELECT
     gender,
     COUNT(customer_key)
FROM gold.dim_customers
GROUP BY gender

--find total products by category
SELECT 
       category,
       COUNT(product_key)
FROM gold.dim_products
GROUP BY category

--what is the avg costs in each category
SELECT 
       category,
       AVG(cost)
FROM gold.dim_products
GROUP BY category

--what is the toal revenue generated for each category
SELECT 
     p.category,
     SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
        ON s.product_key = p.product_key
GROUP BY p.category

--find total revenue is generated by each customer
SELECT 
     c.customer_key,
     c.first_name,
     c.last_name,
     SUM(s.sales_amount) as total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
        ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name

--what is the distribution of sold items across countries
SELECT 
     c.country,
     SUM(s.quantity) as total_items
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
        ON s.customer_key = c.customer_key
GROUP BY c.country
